runtime: python37

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  expiration: 2d

- url: /static/FrizQuadrataStd.otf
  static_files: static/FrizQuadrataStd.otf
  upload: static/FrizQuadrataStd.otf
  mime_type: application/x-font-otf
  expiration: 100d

- url: /static/(.*\.png)$
  static_files: static/\1
  upload: static/.*\.png$
  expiration: 100d

- url: /static
  static_dir: static
  expiration: 2d

- url: /howitworks\.html
  static_files: templates/howitworks.html
  upload: templates/howitworks\.html

- url: /startrank
  script: auto
  secure: always

- url: /rank
  script: auto
  secure: always

- url: /builder
  script: auto

- url: /loadgroups
  script: auto
  secure: always

- url: .*
  script: auto
