application: ctraidprogress
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

default_expiration: "2d"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /resources/FrizQuadrataStd.otf
  static_files: resources/FrizQuadrataStd.otf
  upload: resources/FrizQuadrataStd.otf
  mime_type: application/x-font-otf
  expiration: 100d

- url: /resources/(.*\.png)$
  static_files: resources/\1
  upload: resources/.*\.png$
  expiration: 100d

- url: /resources
  static_dir: resources

- url: /howitworks\.html
  static_files: templates/howitworks.html
  upload: templates/howitworks\.html

- url: /tier17\.html
  static_files: templates/tier17.html
  upload: templates/tier17\.html

- url: /tier18\.html
  static_files: templates/tier18.html
  upload: templates/tier18\.html

- url: /tier19\.html
  static_files: templates/tier19.html
  upload: templates/tier19\.html

- url: /startrank
  script: main.app
  login: admin

- url: /rank
  script: main.app
  login: admin

- url: /builder
  script: main.app
  login: admin

- url: /loadgroups
  script: main.app
  login: admin

- url: /fixgroupnames
  script: main.app
  login: admin

- url: /mergedb
  script: main.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: lxml
  version: "latest"
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: ssl
  version: latest

skip_files:
- ^image_templates
