runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  expiration: 2d

- url: /static/FrizQuadrataStd.otf
  static_files: static/FrizQuadrataStd.otf
  upload: static/FrizQuadrataStd.otf
  mime_type: application/x-font-otf
  expiration: 100d

- url: /static/(.*\.png)$
  static_files: static/\1
  upload: static/.*\.png$
  expiration: 100d

- url: /static
  static_dir: static
  expiration: 2d

- url: /howitworks\.html
  static_files: templates/howitworks.html
  upload: templates/howitworks\.html

- url: /startrank
  script: main.app
  login: admin

- url: /rank
  script: main.app
  login: admin

- url: /builder
  script: main.app
  login: admin

- url: /loadgroups
  script: main.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: pycrypto
  version: latest
- name: ssl
  version: latest

skip_files:
- ^image_templates
